@startchen Consesionario de Autos

left to right direction

entity Vehiculo {
  numeroBastidor <<key>>
  Modelo
  Precio
}

entity Descuento { 
  Id
  Porcentaje
  Descripcion
}

entity Marca {
  Nombre <<key>>
}

entity Modelo {
  Nombre <<key>>
  Marca
}

entity Equipaje {
  Modelo
  Accesorio
  Extra
  Precio
}

entity DatoTecnico {
  Dato
  Valor
}

entity ServicioOficial {
  NIF
  Nombre
  Domicilio
}

entity Vendedor {
  Cedula
  Nombre
  Consesionario
}

entity Consesionario {
  Nombre
  Direccion
}

entity DescuentoVehiculo {
  Vehiculo <<derived>>
  Descuento
}

Vehiculo -(1,N)- DescuentoVehiculo
Descuento -(1,N)- DescuentoVehiculo
Vehiculo -(1,1)- Modelo
Marca -(1,1)- Modelo
Modelo -(N,1)- Equipaje
@endchen
