@startuml DiagramaEntidadRelacion

entity Stock{
  Automovil <<PK, FK>>
  Empresa <<PK, FK>>
}

entity Automovil {
  numeroBastidor <<PK>>
  Modelo <<FK>>
  Precio
  Estado
}

entity Descuento { 
  Id <<PK>>
  Porcentaje
  Descripcion
  FechaFin
  Estado
}

entity Marca {
  Nombre <<PK>>
}

entity Modelo {
  Id <<PK>>
  Marca <<FK>> 
  Nombre <<UNIQUE>>
}

entity Equipaje {
  Id <<PK>>
  Modelo <<FK>>
  Accesorio
  Extra
  Precio
}

entity Vendedor {
  Cedula <<PK>>
  Empresa <<FK>>
  Nombre
  Domicilio
  Correo
}

entity Venta {
  Id <<PK>>
  Vendedor <<FK>>
  Automovil <<FK, UNIQUE>>
  FechaEntrega
  FechaVenta
  Matricula
  Encargo
}

entity Factura {
  Id <<PK>>
  Venta <<FK>>
  PrecioAutomovil
  Total
  FechaEmision
  MetodoPago
}

entity ExtrasAplicados {
  Factura <<PK, FK>>
  Equipaje <<PK, FK>>
  Precio
}

entity DescuentoAplicado {
  Factura <<PK, FK>>
  Descuento <<PK, FK>>
  Porcentaje
}

entity FichaTecnica {
  Modelo <<PK FK>>
  Cilindrada
  Potencia
  Motor
  Combustible
  Carroceria
  Color
}

entity Empresa {
  NIF <<PK>>
  Nombre
  Direccion
}

entity Consesionario {
  Empresa <<PK, FK>>
  Marca <<PK, FK>>
}

entity Servicio {
  Empresa <<PK, FK>>
  Marca <<PK, FK>>
}

entity DescuentoAutomovil {
  Automovil <<PK, FK>>
  Descuento <<PK, FK>>
}

hide methods

Empresa -- Stock: (1,N)
Empresa -- Vendedor: (1,N)
Empresa -- Consesionario: (1,N)
Empresa -- Servicio: (1,N)
Automovil -up- Stock: (1,N)
Automovil -- Venta: (1,1)
Automovil -- Modelo: (N,1)
Modelo -- Equipaje: (1,N)
Modelo -- FichaTecnica: (1,1)
Vendedor -- Venta: (1,N)
Consesionario -- Marca: (1,N)
Servicio -- Marca: (1,N)
Marca -- Modelo: (1,N)
Factura -- Venta: (1,1)
Factura -- ExtrasAplicados: (1,N)
Equipaje -- ExtrasAplicados: (1,N)
DescuentoAplicado -- Factura: (1,N)
DescuentoAplicado -- Descuento: (1,N)
DescuentoAutomovil -- Automovil: (1,N)
DescuentoAutomovil -- Descuento: (1,N)

@enduml
